apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-sample
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  providerConfig:
    value:

      apiVersion: solas.cluster.k8s.io/v1alpha1
      kind: SolasClusterProviderSpec
      metadata:
        labels:
          controller-tools.k8s.io: "1.0"
        name: cluster-0
      spec:
