apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: control-plane-0
spec:
  versions:
    kubelet: 1.11.2
    controlPlane: 1.11.2 
  providerSpec:
    value:
      apiVersion: solas.cluster.k8s.io/v1alpha1
      kind: SolasMachineProviderSpec
      metadata:
        labels:
          controller-tools.k8s.io: "1.0"
        name: control-plane-0
      spec:
        host: 127.0.0.1
        username: root
        privateKeySecret: cluster-private-key
